### ISSUE TITLE
Possible to distinguish between internal drag and drag from external?

### ISSUE THREAD

**Issue by UweKeim** [oozcitak/imagelistview#183]
The `OnDragEnter` method is both called for dragging an image inside the image list view as well as when dragging an image from Windows Explorer into the image list view.

In both cases a call to `e.Data.GetDataPresent(DataFormats.FileDrop)` returns `true`.

My goal is to allow internal dragging but disable external dragging into my application.

**My question:**

Is there any way to reliable detect when dragging from external?

**Comment by UweKeim** [comment]
BTW: Even when always setting `e.Effect = DragDropEffects.None` in the `OnDragEnter` method, the dragging still suceeds.

Seems that the control does not validate the values of the passed event arguments object?!

**Comment by oozcitak** [comment]
Did you try setting the `AllowDrop` property of the control to `false`?

**Comment by UweKeim** [comment]
I never even considered this, since I expected this to also disable the internal dragging.

I'll try, thanks a lot.

**Comment by oozcitak** [comment]
It shouldn't. For internal dragging there is `AllowDrag`.

**Comment by UweKeim** [comment]
In my tests, if I set:

    AllowDrag = true;
    AllowDrop = false;

I was unable to reorder the images internally.

**Comment by ab-tools** [comment]
In the current version 13.4.0 available through NuGet this bug seems not to be fixed yet.

If I set

    AllowDrag = true;
    AllowDrop = false;

I cannot drag items around, I need to enabled `AllowDrop` as well, but then also external items can be dropped (which I don't want).

Can you confirm that the current NuGet version does not have this bug fixed yet?
If not, do you plan to release a new version to NuGet soon?

Thanks!
Andreas

**Comment by ab-tools** [comment]
Hm, I just tried the latest source code, but also there it seems not to work:
Do I need to do something else to enable internal items dragging beside setting `AllowDrag` to `true`?

**Comment by oozcitak** [comment]
Sorry it took so long to fix this issue.

**Comment by ab-tools** [comment]
Thanks, will give it another try!

I was just confused as this issue had been closed already by a commit on 10 Dec 2018:
So I expected it to be done already. :-)

Do you also plan to release a new NuGet package with this fix now?

**Comment by oozcitak** [comment]
I am not sure why I closed the issue without fixing or commenting. It should have been a mistake. My apologies to both of you.

As to the fix: I added a new property to the control, `AllowItemReorder` to better convey the intent. `AllowDrag` is now marked obsolete. I just released a new nuget package with the fix.

**Comment by ab-tools** [comment]
Thanks a lot for your quick reply again!

I've tried it (compiled directly from source), but seems not to work for me yet with `AllowItemReorder=True` and `AllowDrop=False`.

I've attached you my example project again, dragging list-internal items around seems not to work for me yet, but maybe I've done something wrong?

[ImageListViewTest.zip](https://github.com/oozcitak/imagelistview/files/3874197/ImageListViewTest.zip)

**Comment by oozcitak** [comment]
Latest commit should fix this. I have decoupled `AllowItemReorder` from `AllowDrop` completely. So the above table became:

AllowItemReorder | AllowDrop | Result
----|----|----
`true` | `true` | Allows moving selected items within the control. Also allows dragging items out of the control and dropping external items into the control.
`true` | `false` | Allow moving selected items within the control. Drag&drop is disabled.
`false` | `true` | Items within the control can not be moved. But items can be dragged out of the control and extermal items can be dropped into the control.
`false` | `false` | Items within the control can not be moved.  Drag&drop is disabled.

**Comment by ab-tools** [comment]
Thanks a lot, Ozgur, works perfect for me now! 👍

A quick question if you don't mind:
In the `DropItemEventArgs` of the `DropItems` event I get the target index of the items being drop.
Would it be possible to add also the source index of the items being dropped (so where those items were before)?

The reason is that I need to manage a separate list in the background based on the drag & drop operations of the items. Having also the source index (not only the target one) of the items being dropped would therefore help a lot.

**Comment by oozcitak** [comment]
`DropItems` is called before the items are actually moved to their new positions. So you can get original item indices with the `Index` property of items. After items are moved, a second event is called `DropComplete` which also includes the same list of items but with their indices updated to their new positions. See if you are able to solve your issue with these two events. Otherwise let me know please.

A single source index is not possible because the control allows complex selections with the control key.

**Comment by ab-tools** [comment]
Makes absolutely sense what you write: `Index` property should indeed be enough in this case - will give it a try!

Thanks a lot for your support, much appreciated!
Andreas
