### ISSUE TITLE
How ZoomIn & ZoomOut to image selected?

### ISSUE THREAD

**Issue by Sixerito** [oozcitak/imagelistview#199]
I like ZoomIn & ZoomOut the image selected.

Can it possible?

Thank you in advance

**Comment by oozcitak** [comment]
How do you mean?

**Comment by Sixerito** [comment]
Can I do ZoomIn & ZoomOut in the image selected?

**Comment by Sixerito** [comment]
¿?¿?

**Comment by oozcitak** [comment]
I have no idea what you are asking. I wanted you to clarify; you posted the same question with the exact same words. How do you expect me to help you, if I can't understand you?

If you really have an issue, please answer the following questions:

- What is the expected behavior?

- What is the actual behavior?

- If this is a bug, list the steps to reproduce the problem:
1.
2.
3.
